### ISSUE TITLE
It's really good, why stop updating?

### ISSUE THREAD

**Issue by lovestorymeetsvivalavida** [uehaj/dart-saga#1]

**Comment by uehaj** [comment]
thanks for your response.
The reason is, i met a serious problem that is difficult to solve.
When execute takeLatest or takeEvery effects following sequence runs

 (1) a saga yields takeLatest/takeEvery effect with an ACTION name which is expected to be receive.
 (2) In the support library, yields a fork effect.
 (3) Runtime initiate an isolate which is expected to receive the ACTION.
 (4) initiated isolate starts to wait to receive the ACTION.

If another saga(Isolate) yields a put action between (1) to (3), it is missed.
The time rug are not so small to ignore(ti takes some handled milli secs).
Probably introduce some queue-wise something solves this, but it may gain performance overheads.

I started to thinks that is it better to implement with async way? not use Isolate.
Probably you know at Dart 2.0.0-dev 55, isolate support on browser(dart2js) are removed.
That is another reason to suspend development.
any ideas are welcome,
thx

**Comment by lovestorymeetsvivalavida** [comment]
Got it，thanks!
